#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  7 16:20:30 2019

@author: katayamaryotaro
"""

#Cory Althoff Chapter 8 Challenge 

#practice1
import statistics

list = [1,3,5,7,9,11]

result1 = statistics.stdev(list)
result2 = statistics.variance(list)
print(result1)
print(result2)

"""
import statistics

data = [14, 3, 11, 133, 4]

result = statistics.median_low(data)

print(result)
"""

#満点回答か。

#practice2
import module_cube

print(module_cube.cubed(2))

"""
import cubed

result = cubed.cube_it(3)
print(result)
"""

"""
def cube_it(x):
    return x ** 3
"""

#同じく満点回答か。
#resultに一度代入してそれをprintしているがこの短さのコードでは問題にならないと思料。
#モジュール作成時にファイル名に.pyをつけなければpythonは認識しない。


